baseURL: https://mrphys.github.io/homepage/
title: Translational Cardiac MRI Group
menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: publications
    name: Publications
    url: /publications/
    weight: 20
  - identifier: people
    name: People
    url: /people/
    weight: 30
params:
  description: Developing and validating novel methods of imaging the cardiovascular
    system
  img_home: img/home/banner.jpg
  img_404: img/404.jpg
  sponsors:
  - img/sponsors/ucl.png
  - img/sponsors/bhf.png
  - img/sponsors/gosh.png
  - img/sponsors/royalfree.png
  email: rmhitly@ucl.ac.uk
  social:
    github: mrphys
  highlighted_pubs:
    1:
      title: Fully automated measurement of aortic pulse wave velocity from routine
        cardiac MRI studies.
      year: 2025
      journal: Magnetic resonance imaging
      link: https://doi.org/10.1016/j.mri.2025.110442
    2:
      title: A lumped parameter model of the coronary circulation incorporating time-varying
        resistance, intramyocardial pressure and vascular compliance.
      year: 2025
      journal: Journal of biomechanics
      link: https://doi.org/10.1016/j.jbiomech.2025.112679
    3:
      title: 'Transthyretin amyloid cardiomyopathy: natural history and treatment
        response assessed by cardiovascular magnetic resonance.'
      year: 2025
      journal: European heart journal
      link: https://doi.org/10.1093/eurheartj/ehaf412
    4:
      title: 'Defining diastolic dysfunction post-Fontan: Threshold, risk factors,
        and associations with outcomes.'
      year: 2025
      journal: American heart journal
      link: https://doi.org/10.1016/j.ahj.2025.07.007
    5:
      title: 'Strategies to enhance recruitment of female participants to cardiovascular
        research: a joint British Cardiovascular Societies'' consensus document in
        collaboration with the British Heart Foundation Clinical Research Collaborative.'
      year: 2025
      journal: Heart (British Cardiac Society)
      link: https://doi.org/10.1136/heartjnl-2024-325545
    6:
      title: Polyacrylamide Gel Calibration Phantoms for Quantification in Sodium
        MRI.
      year: 2025
      journal: NMR in biomedicine
      link: https://doi.org/10.1002/nbm.70056
    7:
      title: Cardiopulmonary Exercise Testing With Exercise Echocardiography to Assess
        Treatment Response in Transthyretin Amyloid Cardiomyopathy.
      year: 2025
      journal: JACC. Heart failure
      link: https://doi.org/10.1016/j.jchf.2025.01.020
    8:
      title: 'Predicting Peri-Operative Cardiorespiratory Adverse Events in Children
        with Idiopathic Pulmonary Arterial Hypertension Undergoing Cardiac Catheterization
        Using Echocardiography: A Cohort Study.'
      year: 2025
      journal: Pediatric cardiology
      link: https://doi.org/10.1007/s00246-024-03447-3
    9:
      title: A machine learning algorithm for creating isotropic 3D aortic segmentations
        from routine cardiac MR localizers.
      year: 2025
      journal: Magnetic resonance imaging
      link: https://doi.org/10.1016/j.mri.2024.110253
    10:
      title: Cardiac MRI Predictors of Arrhythmic Sudden Cardiac Events in Patients
        With Fontan Circulation.
      year: 2024
      journal: Journal of the American College of Cardiology
      link: https://doi.org/10.1016/j.jacc.2024.08.063
