baseURL: https://mrphys.github.io/homepage/
title: Translational Cardiac MRI Group
menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: publications
    name: Publications
    url: /publications/
    weight: 20
  - identifier: people
    name: People
    url: /people/
    weight: 30
params:
  description: Developing and validating novel methods of imaging the cardiovascular
    system
  img_home: img/home/banner.jpg
  img_404: img/404.jpg
  sponsors:
  - img/sponsors/ucl.png
  - img/sponsors/bhf.png
  - img/sponsors/gosh.png
  - img/sponsors/royalfree.png
  email: rmhitly@ucl.ac.uk
  social:
    github: mrphys
  highlighted_pubs:
    1:
      title: 'Current State of RV Multimodality Imaging in Pediatric Pulmonary Hypertension:
        Current Evidence, Knowledge Gaps, and Future Research Directions.'
      year: 2026
      journal: Circulation. Cardiovascular imaging
      link: https://doi.org/10.1161/CIRCIMAGING.125.019264
    2:
      title: 'Open-Source Pre-Clinical Image Segmentation: Mouse cardiac MRI datasets
        with a deep learning segmentation framework.'
      year: 2026
      journal: 'Journal of cardiovascular magnetic resonance : official journal of
        the Society for Cardiovascular Magnetic Resonance'
      link: https://doi.org/10.1016/j.jocmr.2026.102706
    3:
      title: Myocardial Amyloid Burden in Transthyretin Amyloidosis.
      year: 2026
      journal: Journal of the American College of Cardiology
      link: https://doi.org/10.1016/j.jacc.2025.10.054
    4:
      title: Atrial Mechanical Contraction Predicts Cerebrovascular Risk in Patients
        With Transthyretin Amyloid Cardiomyopathy and Sinus Rhythm.
      year: 2026
      journal: Journal of the American College of Cardiology
      link: https://doi.org/10.1016/j.jacc.2025.12.033
    5:
      title: 'Systemic sclerosis-associated pulmonary arterial hypertension and pulmonary
        fibrosis: exploring biomarker discriminators with advanced omics in a Caucasian
        cohort.'
      year: 2026
      journal: Frontiers in immunology
      link: https://doi.org/10.3389/fimmu.2026.1755076
    6:
      title: 'Transthyretin amyloid cardiomyopathy: natural history and treatment
        response assessed by cardiovascular magnetic resonance.'
      year: 2025
      journal: European heart journal
      link: https://doi.org/10.1093/eurheartj/ehaf412
    7:
      title: 'Defining diastolic dysfunction post-Fontan: Threshold, risk factors,
        and associations with outcomes.'
      year: 2025
      journal: American heart journal
      link: https://doi.org/10.1016/j.ahj.2025.07.007
    8:
      title: Fully automated measurement of aortic pulse wave velocity from routine
        cardiac MRI studies.
      year: 2025
      journal: Magnetic resonance imaging
      link: https://doi.org/10.1016/j.mri.2025.110442
    9:
      title: Increased Body Mass Index and Ventricular Cardiac Magnetic Resonance
        Characteristics in Adults With Fontan Circulation.
      year: 2025
      journal: JACC. Advances
      link: https://doi.org/10.1016/j.jacadv.2025.102094
    10:
      title: 'Strategies to enhance recruitment of female participants to cardiovascular
        research: a joint British Cardiovascular Societies'' consensus document in
        collaboration with the British Heart Foundation Clinical Research Collaborative.'
      year: 2025
      journal: Heart (British Cardiac Society)
      link: https://doi.org/10.1136/heartjnl-2024-325545
